version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: "express-api"
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    volumes: 
      - /usr/data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null # --quiet
    expose:
      - 27017